import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Tabs from '../components/Tabs';
import Slider from '../components/Slider';
import Checkbox from '../components/Checkbox/Checkbox';
import Accordion from '../components/Accordion';
import Dialog from '../components/Dialog';
import HoverCard from '../components/HoverCard';
import ContextMenu from '../components/ContextMenu';
import Popover from '../components/Popover';
import ToggleGroup from '../components/ToggleGroup';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className="mb-12 font-mono text-3xl text-white">Radix components with Tailwind CSS Modules</h1>
        <div className="grid w-full grid-cols-3 gap-3 px-6 mx-auto max-w-7xl">
          <div className="flex flex-col items-center justify-center w-full p-4 mx-auto duration-300 bg-gray-200 shadow-2xl focus-within:bg-indigo-200 rounded-xl">
            <Accordion />
          </div>
          <div className="flex flex-col items-center justify-center w-full p-4 mx-auto duration-300 bg-gray-200 shadow-2xl focus-within:bg-indigo-200 rounded-xl">
            <ContextMenu />
          </div>
          <div className="flex flex-col items-center justify-start w-full mx-auto overflow-hidden bg-gray-200 shadow-2xl rounded-xl">
            <Tabs />
          </div>
          <div className="flex flex-col items-center justify-center w-full p-4 mx-auto duration-300 bg-gray-200 shadow-2xl focus-within:bg-indigo-200 rounded-xl">
            <Slider />
          </div>
          <div className="flex flex-col items-center justify-center w-full p-4 mx-auto duration-300 bg-gray-200 shadow-2xl focus-within:bg-indigo-200 rounded-xl">
            <Dialog />
          </div>
          <div className="flex flex-col items-center justify-center w-full p-4 mx-auto duration-300 bg-gray-200 shadow-2xl focus-within:bg-indigo-200 rounded-xl">
            <HoverCard />
          </div>
          <div className="flex flex-col items-center justify-center w-full p-4 mx-auto duration-300 bg-gray-200 shadow-2xl focus-within:bg-indigo-200 rounded-xl">
            <Checkbox />
          </div>
          
          <div className="flex flex-col items-center justify-center w-full p-4 mx-auto duration-300 bg-gray-200 shadow-2xl focus-within:bg-indigo-200 rounded-xl">
            <Popover />
          </div>
          <div className="flex flex-col items-center justify-center w-full p-4 mx-auto duration-300 bg-gray-200 shadow-2xl focus-within:bg-indigo-200 rounded-xl">
            <ToggleGroup />
          </div>
        </div>
      </main >

    </div >
  )
}

export default Home
